### ISSUE TITLE
[BUG] Opensearch dashboards notifications plugin on docker does not work

### ISSUE THREAD

**Issue by joriham** [opensearch-project/opensearch-plugins#161]
**Describe the bug**

(this ticket was transferred from Opensearch to Dashboards, but I cannot see the original via search this ticket so I recreated)

After creating a channel and alarms etc to my belief by the book nothing works. This is a docker version of open search + dashboards and dockerhub official repo.

I've a webhook and email configuration, both fails timeout 30000ms error on GUI.

When I exec bash at container, I can use CURL to send webhook call to MS TEAMS generated webhook and get alert in the MS Teams channel. It proves that container => Internet => MS TEAMS is perfectly working, so IMO it must be something in the code.

With TCPDUMP I cannot see anything going out from container.

Logs are attached to end..

**To Reproduce**
0. Use Docker version of Open-search dashboards, I don't know if problem is with non-docker version.
1. Go to "Opensearch plugins / notifications"
2. Click on "Create channel"
3. Create Webhook-type channel to a valid webhook, for example Teams
4. Press "Send test message"
5. See the error after 30s

![image](https://user-images.githubusercontent.com/90329114/184835195-4a050f16-4d37-4708-8573-4df7b6a505dc.png)

After "Send test message"

![image](https://user-images.githubusercontent.com/90329114/184835317-026281b4-2d0c-4099-8a6e-d37cd64e0ffa.png)
![image](https://user-images.githubusercontent.com/90329114/184835359-1ff9660b-987f-47db-ab46-b9f23ef783a2.png)

After second send
![image](https://user-images.githubusercontent.com/90329114/184835554-395aa5ae-e1cc-49b9-b286-68a5ec901b28.png)

**Expected behavior**
Well Webhook (and email) should work so Teams channel should have test message and email too if email out is tested.

**OpenSearch Version**
Not relevant but docker pull'd same time as Dashboards with "latest"-tag

**Dashboards Version**
            "Labels": {
                "org.label-schema.build-date": "2022-06-30T22:04:43Z",
                "org.label-schema.description": "4011",
                "org.label-schema.license": "Apache-2.0",
                "org.label-schema.name": "opensearch-dashboards",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "https://opensearch.org",
                "org.label-schema.vcs-url": "https://github.com/opensearch-project/OpenSearch-Dashboards",
                "org.label-schema.vendor": "Amazon",
                "org.label-schema.version": "2.1.0"

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: docker on Ubuntu 22.04.4 LTS

**Additional context**

Logs
`
{"type":"error","@timestamp":"2022-08-16T08:33:52Z","tags":[],"pid":1,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toError (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:143:19)\n    at HapiResponseAdapter.toHapiResponse (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:97:19)\n    at HapiResponseAdapter.handle (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:92:17)\n    at Router.handle (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:164:34)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at handler (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:124:50)\n    at exports.Manager.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at Object.internals.handler (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at exports.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at Request._lifecycle (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:371:32)\n    at Request._execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:281:9)"},"url":"http://xxx.yyy.hosting.fi/api/notifications/test_message/1NzJpYIBCI5M2_14qImg","message":"Internal Server Error"}
{"type":"response","@timestamp":"2022-08-16T08:33:52Z","tags":[],"pid":1,"method":"get","statusCode":500,"req":{"url":"/api/notifications/test_message/1NzJpYIBCI5M2_14qImg","method":"get","headers":{"connection":"upgrade","host":"xxx.yyy.hosting.fi","x-real-ip":"aaa.bbb.ccc.ddd","x-forwarded-for":"aaa.bbb.ccc.ddd","x-forwarded-proto":"https","x-forwarded-host":"xxx.yyy.hosting.fi","x-forwarded-port":"443","sec-ch-ua":"\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Microsoft Edge\";v=\"104\"","content-type":"application/json","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","osd-version":"2.1.0","sec-ch-ua-platform":"\"Windows\"","accept":"*/*","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards","accept-encoding":"gzip, deflate, br","accept-language":"fi,en-US;q=0.9,en;q=0.8","securitytenant":""},"remoteAddress":"172.17.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards"},"res":{"statusCode":500,"responseTime":22730,"contentLength":9},"message":"GET /api/notifications/test_message/1NzJpYIBCI5M2_14qImg 500 22730ms - 9.0B"}
{"type":"response","@timestamp":"2022-08-16T08:34:15Z","tags":[],"pid":1,"method":"delete","statusCode":200,"req":{"url":"/api/notifications/delete_configs?config_id_list=1NzJpYIBCI5M2_14qImg","method":"delete","headers":{"connection":"upgrade","host":"xxx.yyy.hosting.fi","x-real-ip":"aaa.bbb.ccc.ddd","x-forwarded-for":"aaa.bbb.ccc.ddd","x-forwarded-proto":"https","x-forwarded-host":"xxx.yyy.hosting.fi","x-forwarded-port":"443","sec-ch-ua":"\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Microsoft Edge\";v=\"104\"","content-type":"application/json","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","osd-version":"2.1.0","sec-ch-ua-platform":"\"Windows\"","accept":"*/*","origin":"https://xxx.yyy.hosting.fi","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards","accept-encoding":"gzip, deflate, br","accept-language":"fi,en-US;q=0.9,en;q=0.8","securitytenant":""},"remoteAddress":"172.17.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards"},"res":{"statusCode":200,"responseTime":14,"contentLength":9},"message":"DELETE /api/notifications/delete_configs?config_id_list=1NzJpYIBCI5M2_14qImg 200 14ms - 9.0B"}
{"type":"response","@timestamp":"2022-08-16T08:34:59Z","tags":[],"pid":1,"method":"post","statusCode":200,"req":{"url":"/api/notifications/create_config","method":"post","headers":{"connection":"upgrade","host":"xxx.yyy.hosting.fi","x-real-ip":"aaa.bbb.ccc.ddd","x-forwarded-for":"aaa.bbb.ccc.ddd","x-forwarded-proto":"https","x-forwarded-host":"xxx.yyy.hosting.fi","x-forwarded-port":"443","content-length":"441","sec-ch-ua":"\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Microsoft Edge\";v=\"104\"","content-type":"application/json","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","osd-version":"2.1.0","sec-ch-ua-platform":"\"Windows\"","accept":"*/*","origin":"https://xxx.yyy.hosting.fi","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards","accept-encoding":"gzip, deflate, br","accept-language":"fi,en-US;q=0.9,en;q=0.8","securitytenant":""},"remoteAddress":"172.17.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards"},"res":{"statusCode":200,"responseTime":21,"contentLength":9},"message":"POST /api/notifications/create_config 200 21ms - 9.0B"}
{"type":"error","@timestamp":"2022-08-16T08:34:59Z","tags":[],"pid":1,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toError (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:143:19)\n    at HapiResponseAdapter.toHapiResponse (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:97:19)\n    at HapiResponseAdapter.handle (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:92:17)\n    at Router.handle (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:164:34)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at handler (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:124:50)\n    at exports.Manager.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at Object.internals.handler (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at exports.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at Request._lifecycle (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:371:32)\n    at Request._execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:281:9)"},"url":"http://xxx.yyy.hosting.fi/api/notifications/test_message/1dzKpYIBCI5M2_14rolN","message":"Internal Server Error"}
{"type":"response","@timestamp":"2022-08-16T08:34:59Z","tags":[],"pid":1,"method":"get","statusCode":500,"req":{"url":"/api/notifications/test_message/1dzKpYIBCI5M2_14rolN","method":"get","headers":{"connection":"upgrade","host":"xxx.yyy.hosting.fi","x-real-ip":"aaa.bbb.ccc.ddd","x-forwarded-for":"aaa.bbb.ccc.ddd","x-forwarded-proto":"https","x-forwarded-host":"xxx.yyy.hosting.fi","x-forwarded-port":"443","sec-ch-ua":"\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Microsoft Edge\";v=\"104\"","content-type":"application/json","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","osd-version":"2.1.0","sec-ch-ua-platform":"\"Windows\"","accept":"*/*","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards","accept-encoding":"gzip, deflate, br","accept-language":"fi,en-US;q=0.9,en;q=0.8","securitytenant":""},"remoteAddress":"172.17.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards"},"res":{"statusCode":500,"responseTime":30011,"contentLength":9},"message":"GET /api/notifications/test_message/1dzKpYIBCI5M2_14rolN 500 30011ms - 9.0B"}
{"type":"response","@timestamp":"2022-08-16T08:35:29Z","tags":[],"pid":1,"method":"delete","statusCode":200,"req":{"url":"/api/notifications/delete_configs?config_id_list=1dzKpYIBCI5M2_14rolN","method":"delete","headers":{"connection":"upgrade","host":"xxx.yyy.hosting.fi","x-real-ip":"aaa.bbb.ccc.ddd","x-forwarded-for":"aaa.bbb.ccc.ddd","x-forwarded-proto":"https","x-forwarded-host":"xxx.yyy.hosting.fi","x-forwarded-port":"443","sec-ch-ua":"\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Microsoft Edge\";v=\"104\"","content-type":"application/json","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","osd-version":"2.1.0","sec-ch-ua-platform":"\"Windows\"","accept":"*/*","origin":"https://xxx.yyy.hosting.fi","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards","accept-encoding":"gzip, deflate, br","accept-language":"fi,en-US;q=0.9,en;q=0.8","securitytenant":""},"remoteAddress":"172.17.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54","referer":"https://xxx.yyy.hosting.fi/dashboards/app/notifications-dashboards"},"res":{"statusCode":200,"responseTime":23,"contentLength":9},"message":"DELETE /api/notifications/delete_configs?config_id_list=1dzKpYIBCI5M2_14rolN 200 23ms - 9.0B"}

`

**Comment by joriham** [comment]
Testing from container with CURL:
$ curl -H 'Content-Type: application/json' -d '{"text": "Hello World from OS-dashboard container for github ticket"}' https://inmicsnebula.webhook.office.com/webhookb2/2782
1

and from Teams
![image](https://user-images.githubusercontent.com/90329114/184851942-4386fec5-9c81-40a0-b6ca-21c01d6ffbac.png)

Meaning that host and container can talk to teams with exactly the same URL given to notification channel webhook

**Comment by dblock** [comment]
I'll move this to notifications. I think that's where this issue is?
